### ISSUE TITLE
import docker images

### ISSUE THREAD

**Issue by dciangot** [comp-dev-cms-ita/images#1]
- [ ]  cache
- [ ] schedd
- [x] wn
- [x] jlab

**Comment by dciangot** [comment]
- [ ] cache
- [ ] schedd
- [ ] wn
- [ ] jlab

**Comment by MircoT** [comment]
In progress porting of WN image with Dask: https://github.com/DODAS-TS/dodas-docker-images/tree/dask_cvmfs/docker/htcondor/dask
